version: "3.8"
services:
  db:
    image: postgres
    container_name: local_postgres
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 8gag
    volumes:
      - local_pgdata:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    container_name: local_pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - local_pgadmin4data:/var/lib/pgadmin

volumes:
  local_pgdata:
  local_pgadmin4data:
