server:
    port: 8080
    address: 0.0.0.0
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgres:5432/8gag
        username: postgres
        password: postgres
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
